export const permissionsArray = {
  account_master: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  assign_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  party_call: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  all_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
    status: false,
  },
  // sell_orders: {
  //   view_global: false,
  //   view_own: false,
  //   create: false,
  //   edit: false,
  //   delete: false,
  // },
  driver: {
    view_global: false,
    // view_own: false,
    // create: false,
    // edit: false,
    // delete: false,
    // status: false,
  },
  all_complains: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  // payment_folders: {
  //   view_global: false,
  //   view_own: false,
  //   create: false,
  //   edit: false,
  //   delete: false,
  // },
  quality_packaging: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  proforma_invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  reports: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  inventory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchase: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  qp_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  history: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  designer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  printer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  booklet_blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  setup: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
}
export const QualityPermissionsArray = {
  account_master: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  assign_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  party_call: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  all_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    status: false,
  },
  sell_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    status: false,
  },
  order_factory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  quality_packaging: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  proforma_invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  reports: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  inventory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchase: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  history: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  setup: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
}

export const companyOptions = ["Sakshi Creation", "Quality Packaging"]
export const StaticCompanyOptions = ["Sakshi Creation", "Quality Packaging"]
export const printerTypeOption = [
  { label: "Offset", value: 'Offset' },
  { label: "Screen Printing", value: "Screen Printing" },
  { label: "Other", value: "Other" }]

export const ORDER_STATUSES = [
  "Pending",
  "In Progress",
  "Designer",
  // "Paper cutting & Corrugation",
  // "Printer & Corrugation",
  // "Lamination & Corrugation",
  "Paper cutting",
  "Printer",
  "Lamination",
  "Corrugation",
  "Pasting",
  "Rotery",
  "Sloting/rs4",
  // "Printing",
  "Manual pasting",
  "Pinning",
  "Punching",
  "Kanthan",
  "Operator Completed",
  "Completed",
  "On Hold",
  "Canceled",
];

export const processSteps = [
  { key: "design", label: "Design", color: "#27657eff" },
  { key: "paper_cutting", label: "Paper Cutting", color: "#EF4444" },
  { key: "printer", label: "Printer", color: "#8B008B" },
  { key: "lamination", label: "Lamination", color: "#FF69B4" },
  { key: "corrugation", label: "Corrugation", color: "#F59E0B" },
  { key: "pasting", label: "Pasting", color: "#10B981" },
  { key: "rotary", label: "Rotary", color: "#3B82F6" },
  { key: "slotting", label: "Slotting", color: "#8B5CF6" },
  { key: "manual_pasting", label: "Manual Pasting", color: "#06B6D4" },
  { key: "pinning", label: "Pinning", color: "#84CC16" },
  { key: "punching", label: "Punching", color: "#F97316" },
];