export const permissionsArray = {
  account_master: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  assign_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  party_call: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  all_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
    status: false,
  },
  driver: {
    view_global: false,
    // view_own: false,
    // create: false,
    // edit: false,
    // delete: false,
    // status: false,
  },
  all_complains: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  quality_packaging: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  proforma_invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  reports: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  inventory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchase: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  qp_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  history: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  designer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  printer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  booklet_blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  setup: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
}
export const QualityPermissionsArray = {
  account_master: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  assign_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  party_call: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  all_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    status: false,
  },
  order_factory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  quality_packaging: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  proforma_invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  reports: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  inventory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchase: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  history: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  setup: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
}

export const companyOptions = ["Sakshi Creation", "Quality Packaging"] 
export const StaticCompanyOptions = ["Sakshi Creation", "Quality Packaging"] 
export const printerTypeOption = [
  { label: "Offset", value: 'Offset' },
  { label: "Screen Printing", value: "Screen Printing" },
  { label: "Other", value: "Other" }]

export const ORDER_STATUSES = [
    "Paper cutting",
    "Printer",
    "Lamination",
    "Corogation",
    "Pasting",
    "Rotery",
    "Sloting/rs4",
    "Printing",
    "Manual pasting",
    "Pinning",
    "Kanthan",
    "Puching",
    "Pending",
    "In Progress",
    "On Hold",
    "Canceled",
    "Completed",
];