export const permissionsArray = {
  account_master: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  assign_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  party_call: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  all_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  quality_packaging: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  proforma_invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  reports: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  inventory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchase: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  history: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  designer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  printer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  booklet_blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  setup: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
}